### PR TITLE
Fix for #6 (empty directories are not created)

### PR DESCRIPTION
**Pull request by smebberson**
This PR does:

- [x] add basic tests using `tape`
- [x] update `extract-zip` so that empty directories are created

@maxogden, this is now complete.

### CODE REVIEW

**Comment by maxogden** [comment]
awesome, looks good and glad it turned out to be pretty straightforward. gonna merge and then add https://www.npmjs.com/package/standard style

**Comment by smebberson** [comment]
@maxogden, cool. I tried to follow that (not in test/test.js) but that isn't the usual style guide that I follow so I'm unpractised at it.

**Comment by smebberson** [comment]
@maxogden, oh, please let me know when you've published to npm. Thanks!

**Comment by maxogden** [comment]
@smebberson will do. found a regression which is that now that we aren't calling `mkdirp` on every entry, it fails if the initial target folder doesn't exist with a 'directory does not exist' error when it tries to extract the first file in the zip. fixing now

**Comment by smebberson** [comment]
@maxogden, sorry about that! At least you can easily write a test for it now :)

**Comment by maxogden** [comment]
@smebberson hah, true. published as 1.1.0. check out the last couple of commits for the fix i made if youre interested. thanks again

**Pull request merged**
