### PR TITLE
debug@2.2.0 Regular Expression Denial of Service

### PR DESCRIPTION
**Pull request by lisong**
https://snyk.io/test/npm/extract-zip

### CODE REVIEW

**Comment by Ilshidur** [comment]
I would love if this PR was merged. (related to https://github.com/maxogden/extract-zip/issues/48)

**Comment by avindra** [comment]
Please close in favor of

https://github.com/maxogden/extract-zip/pull/52


I believe 2.6.9 or higher must be used as well

**Comment by kirrg001** [comment]
Let's merge this!

**Comment by avindra** [comment]
Please *do not* merge this. The fix is in 2.6.9 or higher

**Comment by kirrg001** [comment]
> nsp check >= 2.6.9 < 3.0.0 || >= 3.1.0

Yes. So let's close this and merge #52 😎

**Pull request closed without merging**
